### ISSUE TITLE
Weird shadowing when metallic map has areas of alpha = 0

### ISSUE THREAD

**Issue by Mysteryem** [Xiexe/Xiexes-Unity-Shaders#10]
There's a weird shadowing that occurs when the alpha value of parts of a metallic map is exactly 0 (1-255 seems to work fine).

Attached is a metallic map that shows this issue.
To reproduce, create a new material using XSToon,
Turn on PBR reflections,
Set the attached metallic map,
Put the material on a quad for easy viewing

![mira_top_metallicsmoothness](https://user-images.githubusercontent.com/495015/50398781-26cac580-0772-11e9-853f-13a7616c3fae.png)
![image](https://user-images.githubusercontent.com/495015/50398986-d7859480-0773-11e9-8d65-262390fe42db.png)

**Comment by Xiexe** [comment]
Looking into it. A fix should be in the 1.6.1 patch.

**Comment by Xiexe** [comment]
Should be fixed in upcoming release.
