### ISSUE TITLE
Sphere maps not rendering correctly for VR

### ISSUE THREAD

**Issue by cubiclestorm** [Xiexe/Xiexes-Unity-Shaders#11]
Sphere maps aren't rendering correctly for VR. Left and right eye separation are off causing the depth to look wrong or have an odd flickering look. You can tell by seeing the difference looking at it with one eye vs both eyes.

**Comment by Xiexe** [comment]
Looking into this now - I'll have it ready by 1.7 release. Will close issue once fixed, assuming I can reproduce it.

**Comment by Xiexe** [comment]
Try reimporting the shader - I think this is a compiler issue, and I can't reproduce it. 

If it still has issues, if you could send me an example project on Discord, that would be helpful, as I said, I can't reproduce it locally.

Xiexe#0426

**Comment by auronx223** [comment]
Re-importing the shader seemed to fix the issue for me.

Originally I had version 1.3 in Unity when copying the new version across, then deleted 1.3 afterwards.

I deleted the folder and re-added it and seems to be working okay.

Thanks.
