### ISSUE TITLE
Using A2C Masked dissolve mask causes shadows not to appear on the mesh behind the transparent parts

### ISSUE THREAD

**Issue by auronx223** [Xiexe/Xiexes-Unity-Shaders#22]
When using the cutoutA2C_Masked shader, the mesh behind the transparent parts seem to have no shadows.
![image](https://user-images.githubusercontent.com/9289155/80496436-1d063300-8961-11ea-92b0-6111671e0d05.png)

For reference here same image with the plain shader without any cutout.
![image](https://user-images.githubusercontent.com/9289155/80496561-445d0000-8961-11ea-822c-4e7b310c78cf.png)

The Albedo image is imported as RGB 24 bit format. Using standard default scene with a single directional light.

**Comment by Xiexe** [comment]
Should now be fixed in 2.2.4
