### ISSUE TITLE
seems to be linked to normal maps and how it reflects something, idk what that something is tho

### ISSUE THREAD

**Issue by treeofdeath** [Xiexe/Xiexes-Unity-Shaders#30]
![Desktop Screenshot 2020 10 12 - 18 50 25 87](https://user-images.githubusercontent.com/72770290/95796810-e24c4900-0cbb-11eb-861a-23413969b833.png)
![Desktop Screenshot 2020 10 12 - 18 50 33 67](https://user-images.githubusercontent.com/72770290/95796812-e2e4df80-0cbb-11eb-95b8-628495948517.png)
![Desktop Screenshot 2020 10 12 - 18 50 37 63](https://user-images.githubusercontent.com/72770290/95796815-e37d7600-0cbb-11eb-89be-617caaf5ca1a.png)
![Desktop Screenshot 2020 10 12 - 18 50 41 87](https://user-images.githubusercontent.com/72770290/95796817-e37d7600-0cbb-11eb-80e5-8854560de10b.png)
seems odd to me, it doesnt do it with every model i own but sometimes this sort of shadow rim-like thing happen. super spooky

**Comment by treeofdeath** [comment]
i have tried playing with every settings on it, lights in unity and etc. but it just doesnt want to give up

**Comment by treeofdeath** [comment]
happens after setting a shadow ramp, ill experiment a bit more

**Comment by treeofdeath** [comment]
![gradient](https://user-images.githubusercontent.com/72770290/95797627-f5601880-0cbd-11eb-950b-ea1f6ac27315.png)
![Desktop Screenshot 2020 10 12 - 19 05 47 06](https://user-images.githubusercontent.com/72770290/95797638-fabd6300-0cbd-11eb-8719-cf7272bd97b6.png)
fixed it via remaking a new gradient linear shadow ramp, ill close this and say im sorry for my own stoupidity, hope it can help anyone in the future who has this issue

**Comment by Xiexe** [comment]
The reason it fixed itself upon making a new ramp is because the script clamps the ramp. It sets the wrap mode to "none."

What you're seeing there is the ramp UV actually bleeding into a wrapped version of the ramp, so it goes from 0-1, and then bleeds over a bit back to 0. 

The fix, for future reference, is just to set the wrap mode in the import settings of the texture.
