### ISSUE TITLE
Where is the package?

### ISSUE THREAD

**Issue by Jorvalt** [Xiexe/Xiexes-Unity-Shaders#33]
All of the releases just have source code, there are no packages to download. Do you expect me to be able to somehow magically package source code?

**Comment by Xiexe** [comment]
Fun Fact:

Unitypackages are glorified zip files. You'd be getting the source code regardless of if it's in a Unitypackage or a zip.

So, no, I don't expect anyone to magically package source code, but I do expect people understand how to unzip a zip file, which most do!

**Comment by SelynCatto** [comment]
It would honestly be a lot easier for people if there did happen to be a unitypackage, even if it's basically a zip file, it makes things a lot easier for the end user, users who don't know how to properly just paste files in, it's kind of confusing, what do you paste, do you paste these files 
![image](https://user-images.githubusercontent.com/71310187/129275332-2a96ad44-f609-4abe-927c-3d516656fb82.png)
or do you just paste the entire folder 
![image](https://user-images.githubusercontent.com/71310187/129275350-2fa865e2-9d96-4411-967d-9b5bedcd208a.png)
